apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS customers;
    CREATE DATABASE IF NOT EXISTS notification;
    CREATE DATABASE IF NOT EXISTS fraud;
    
