apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: postgres-local-pv
    app: postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-local-pv-pvclaim
  labels:
    app: postgres
    type: postgres-pv-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
