apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      type: postgres-pod
  serviceName: postgres-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        type: postgres-pod
    spec:
    
      volumes:
        - name: postgres-vol-mount
          persistentVolumeClaim:
            claimName: postgres-local-pv-pvclaim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-vol-mount
          envFrom:
            - configMapRef:
                name: postgres-configmap
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
       
  
