services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
    - postgres:/data/postgres
    ports:
    - 5432:5432
    networks:
    - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
    - pgadmin:/var/lib/pgadmin
    ports:
    - 5050:80
    networks:
    - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - 9411:9411
    networks:
    - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    networks:
    - spring
  apigw:
    image: prashant24062994/apigw:latest
    container_name: apigw
    ports:
    - 8083:8083
    networks:
    - spring
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - zipkin
    - eureka-server
  eureka-server:
    image: prashant24062994/eureka-server:latest
    container_name: eureka-server
    ports:
    - 9411:9411
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    networks:
    - spring
    depends_on:
    - zipkin
  customer:
    image: prashant24062994/customer:latest
    container_name: customer
    ports:
    - 8080:8080
    networks:
    - spring
    - postgres
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - zipkin
    - eureka-server
    - apigw
  fraud:
    image: prashant24062994/fraud:latest
    container_name: customer
    ports:
    - 8081:8081
    networks:
    - spring
    - postgres
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - zipkin
    - eureka-server
    - apigw
  notification:
    image: prashant24062994/notification:latest
    container_name: notification
    ports:
    - 8082:8082
    networks:
    - spring
    - postgres
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - zipkin
    - eureka-server
    - apigw
    - customer
    - fraud
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
volumes:
  postgres: null
  pgadmin: null