apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: prashant24062994/notification:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
          volumeMounts:
            - name: notification-logs
              mountPath: /var/log/spring-apps/notification

      volumes:
        - name: notification-logs
          hostPath:
            path: /var/log/spring-apps/notification