apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: prashant24062994/fraud:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
          volumeMounts:
            - name: fraud-logs
              mountPath: /var/log/spring-apps/fraud

      volumes:
        - name: customer-logs
          hostPath:
            path: /var/log/spring-apps/fraud
